### ISSUE TITLE
core.definePreset is not a function

### ISSUE THREAD

**Issue by kirkeskov** [xsjcTony/unocss-preset-animations#1]
Hi there

Trying to work with the preset for using shadcn-vue together with unocss, but can't seem to figure what this error is related to.
When my config looks like this:

```javascript
import {
  defineConfig,
  presetIcons,
  presetUno,
  transformerDirectives,
} from "unocss";

import presetAnimations from "unocss-preset-animations";
import { presetShadcn } from "unocss-preset-shadcn";

export default defineConfig({
  presets: [
    presetUno(),
    presetIcons({
      prefix: "i-",
      extraProperties: {
        display: "inline-block",
        "vertical-align": "middle",
      },
    }),
    presetShadcn({
      color: "slate",
    }),
    presetAnimations(),
  ],
  transformers: [transformerDirectives()],
```

I get the following error on npm run dev:

```javascript
/Users/frederikkirkeskov/Sites/hrzn-frontend/node_modules/unocss-preset-animations/dist/index.cjs:188
const presetAnimations = core.definePreset(() => ({
                              ^

TypeError: core.definePreset is not a function
    at /Users/frederikkirkeskov/Sites/hrzn-frontend/node_modules/unocss-preset-animations/dist/index.cjs:188:31
    at evalModule (/Users/frederikkirkeskov/Sites/hrzn-frontend/node_modules/jiti/dist/jiti.js:1:256443)
    at jiti (/Users/frederikkirkeskov/Sites/hrzn-frontend/node_modules/jiti/dist/jiti.js:1:254371)
    at /Users/frederikkirkeskov/Sites/hrzn-frontend/uno.config.js:11:54
    at evalModule (/Users/frederikkirkeskov/Sites/hrzn-frontend/node_modules/jiti/dist/jiti.js:1:256443)
    at jiti (/Users/frederikkirkeskov/Sites/hrzn-frontend/node_modules/jiti/dist/jiti.js:1:254371)
    at loadConfigFile (/Users/frederikkirkeskov/Sites/hrzn-frontend/node_modules/unconfig/dist/index.cjs:162:13)
    at async Object.load (/Users/frederikkirkeskov/Sites/hrzn-frontend/node_modules/unconfig/dist/index.cjs:85:24)
    at async Object.loadConfig (/Users/frederikkirkeskov/Sites/hrzn-frontend/node_modules/@unocss/config/dist/index.cjs:50:18)
    at async Object.reloadConfig (/Users/frederikkirkeskov/Sites/hrzn-frontend/node_modules/@unocss/vite/dist/index.cjs:108:20)
    at async FSWatcher.<anonymous> (/Users/frederikkirkeskov/Sites/hrzn-frontend/node_modules/@unocss/vite/dist/index.cjs:1052:9)

Node.js v20.11.0
``` 

I'm not using TypeScript, unfortunately, maybe this might be related.
Running `unocss@0.58.6`, but seems like it's related to the imports in the dist/index.cjs of this package..

**Comment by xsjcTony** [comment]
It should have nothing to do with whether you are using TypeScript.
It should have something to do with your project environment.
Can you please provide a minimal reproduction on Stackblitz or other alternatives please? I don't see any problem using it myself.
https://stackblitz.com/edit/vitejs-vite-n2ktcb?file=src%2Fcomponents%2FHelloWorld.vue

**Comment by kirkeskov** [comment]
Sorry, there was a wrong @unocss/core installed, due to a separate installation with an older version of of @unocss/preset-icons. My bad, works now.
